-- Runde 2 av ostekatalogen: 156 nye franske oster fra Wikipedias
-- «Liste de fromages français» (700 rader parset, 332 med egen artikkel,
-- 156 med sikker melketype fra Wikidata P186 — resten mangler enten egen
-- artikkel eller entydig melketype og er bevisst utelatt, ikke gjettet).
-- Bilder fra Wikidata P18 (strukturert egenskap, ikke fritekst-søk —
-- langt færre bomtreff enn MediaWiki-søket brukt i forrige runde).
-- Stikkprøve på 15 bilder: 14/15 traff riktig, 1 (Chèvre du Mont-Ventoux)
-- viste seg å være et markedsbilde og fikk img=null i stedet.
-- Genereringsscript: se samtalehistorikk — engangskjøring, ikke i tools/.
insert into public.flayost_cheese_species (name, milk, tex, origin, lat, lng, img) values
  ('Abbaye de Cîteaux', 'Ku', null, 'Côte-d''Or', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20de%20C%C3%AEteaux.JPG'),
  ('Abbaye de la Pierre-Qui-Vire', 'Ku', null, 'Yonne', null, null, null),
  ('Abbaye de Tamié', 'Ku', null, 'Savoie', 45.6871, 6.3043, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20abbaye%20de%20Tami%C3%A9.jpg'),
  ('Mont des Cats', 'Ku', null, 'Nord', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/MontsdesCats%20fromage.jpg'),
  ('Pur Brebis de l''Abbaye de Belloc', 'Sau', null, 'Pyrénées-Atlantiques', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20Belloc%2002.jpg'),
  ('Trappe de Bricquebec', 'Ku', null, 'Normandie', null, null, null),
  ('Trappe Échourgnac', 'Ku', null, 'Dordogne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20Trappe%20%C3%89chourgnac%20-%2020150619%20-%20005.jpg'),
  ('Trappe de Timadeuc', 'Ku', null, 'et Timanoix, Bretagne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromages%20de%20Timadeuc.jpg'),
  ('Aiguille d''Orcières', 'Ku', null, 'Hautes-Alpes', null, null, null),
  ('Aisy Cendré', 'Ku', null, 'Bourgogne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20Aisy%20cendr%C3%A9%2002.jpg'),
  ('Amou', 'Sau', null, 'Gascogne', null, null, null),
  ('Angelot', 'Ku', null, 'Pays d''Auge, Normandie', null, null, null),
  ('Anneau du Vic-Bilh', 'Geit', null, 'Béarn et Gascogne', null, null, null),
  ('Annot', 'Sau', null, 'Alpes-de-Haute-Provence', null, null, null),
  ('Arôme au vin blanc', 'Ku', null, 'Rhône-Alpes', null, null, null),
  ('Arôme de Gêne de Marc', 'Ku', null, 'ou Arôme de Lyon, Rhône-Alpes', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tomme-au-Marc-de-Raisin.jpg'),
  ('Arrigny', 'Ku', null, 'Champagne-Ardenne', null, null, null),
  ('Arthon', 'Geit', null, 'Centre', null, null, null),
  ('Artisons', 'Ku', null, '(fromages aux), Haute-Loire, Cantal', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20aux%20artisous%20du%20Velay.JPG'),
  ('Autun', 'Geit', null, 'Bourgogne', null, null, null),
  ('Barberey', 'Ku', null, 'ou troyen cendré, Champagne', null, null, null),
  ('Barousse', 'Ku', null, 'Pyrénées', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20Barousse.jpg'),
  ('Bargkass', 'Ku', null, 'Vosges', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bargkass%20de%20la%20ferme%20de%20la%20Chapelle%20des%20V%C3%A9s%2001.jpg'),
  ('Beaumont', 'Ku', null, 'Savoie, Haute-Savoie', null, null, null),
  ('Belle des champs', 'Ku', null, 'Aisne, Picardie', null, null, null),
  ('Bergues', 'Ku', null, 'Flandre française', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bergues%28fromage%29.jpg'),
  ('Bleu de Costaros', 'Ku', null, 'Auvergne', null, null, null),
  ('Bleu de Langeac', 'Ku', null, 'Auvergne', null, null, null),
  ('Bleu de Loudes', 'Ku', null, 'Auvergne', null, null, null),
  ('Bleu de Thiézac', 'Ku', null, 'Auvergne', null, null, null),
  ('Bresse Bleu', 'Ku', null, 'Bresse', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bleu%20de%20Bresse%20cheese.jpg'),
  ('Bleu de Corse', 'Sau', null, 'Corse', null, null, null),
  ('Bleu du Quercy', 'Ku', null, 'Quercy', null, null, null),
  ('Bleu de Sainte-Foy', 'Ku', null, 'Savoie', null, null, null),
  ('Bonde de Gâtine', 'Geit', null, 'Poitou', null, null, null),
  ('Bondard', 'Ku', null, 'Normandie', null, null, null),
  ('Bondon', 'Ku', null, 'Normandie', null, null, null),
  ('Bons mayennais', 'Ku', null, 'Mayenne, Pays de Loire', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bons%20Mayennais%20fromage%202.jpg'),
  ('Bosson macéré', 'Sau', null, 'Ardèche (Vivarais) et Bouches-du-Rhône (Crau)', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bosson%20mac%C3%A9r%C3%A9%20sur%20tartine%20de%20pain%20gill%C3%A9e.jpg'),
  ('Boucantrin', 'Ku', null, 'Dauphiné', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Boucantrin%20du%20Dauphin%C3%A9.jpg'),
  ('Bougon', 'Geit', null, 'Poitou', null, null, null),
  ('Bouine', 'Ku', null, 'Sarthe, Pays de Loire', null, null, null),
  ('Boule des moines', 'Ku', null, 'Morvan', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pierre-qui-Vire-2009-10.jpg'),
  ('Boulette de la Pierre-qui-Vire', 'Ku', null, 'Bourgogne', null, null, null),
  ('Brézain', 'Ku', null, 'Haute-Savoie', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Br%C3%A9zain.jpg'),
  ('Brie de Coulommiers', 'Ku', null, 'Île-de-France', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Coulommiers%20lait%20cru.jpg'),
  ('Brie de Montereau', 'Ku', null, 'ou Ville-Saint-Jacques, Île-de-France', null, null, null),
  ('Brie de Nangis', 'Ku', null, 'Île-de-France', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wikicheese%20-%20Brie%20de%20Nangis%20-%2020150515%20-%20013.jpg'),
  ('Brie de Provins', 'Ku', null, 'Île-de-France', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Brie%20de%20Provins%20crop.jpg'),
  ('Brouère', 'Ku', null, 'Vosges', null, null, null),
  ('Bûche du Poitou', 'Geit', null, 'Poitou, Limousin', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Buche%20du%20Poitou.jpg'),
  ('Cachaille', 'Sau', null, 'Provence', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pain%2C%20oignon%20et%20petit%20pot%20de%20cachaille.jpg'),
  ('Cachat', 'Sau', null, 'Comtat Venaissin, Vaucluse', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cachat.jpg'),
  ('Carré d''Aurillac', 'Ku', null, 'Cantal', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Carr%C3%A9%20d%27Aurillac%20-%20debout.JPG'),
  ('Carré de Bray', 'Ku', null, 'Normandie, Seine-Maritime : Gournay-en-Bray, Forges-les-Eaux', null, null, null),
  ('Carré du Poitou', 'Ku', null, 'Poitou', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Carr%C3%A9%20Poitevin.jpg'),
  ('Chabis', 'Geit', null, 'Poitou, Charentes', null, null, null),
  ('Chaussée aux Moines', 'Ku', null, 'Mayenne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chauss%C3%A9e%20aux%20Moines%20%282%29.JPG'),
  ('Chavroux', 'Geit', null, 'Poitou', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chavroux.jpg'),
  ('Chèvre des Alpilles', 'Geit', null, '', null, null, null),
  ('Chèvre du Poitou', 'Geit', null, 'Poitou', null, null, null),
  ('Chèvre du Mont-Ventoux', 'Geit', null, '', null, null, null),
  ('Chèvreton', 'Ku', null, '', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ch%C3%A8vretons%20d%27Ard%C3%A8che%20sur%20le%20march%C3%A9%20d%27Apt.jpg'),
  ('Claquebitou', 'Geit', null, 'Bourgogne', null, null, null),
  ('Confit d''Époisses', 'Ku', null, 'Bourgogne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Confit%20d%27%C3%89poisses.jpg'),
  ('Coussignous', 'Sau', null, 'Var', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Coussignous%2C%20huile%20d%27olive%20et%20fines%20herbes.jpg'),
  ('Dauphin', 'Ku', null, 'Picardie, Nord-Pas-de-Calais', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20Dauphin%2002.jpg'),
  ('Demi-sel', 'Ku', null, 'Pays de Bray, Normandie et Picardie.', null, null, null),
  ('Écorce de sapin', 'Ku', null, 'Franche-Comté', null, null, null),
  ('Édel de Cléron', 'Ku', null, 'Franche-Comté', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Edel%20de%20Cleron%202.jpg'),
  ('Esbareich', 'Sau', null, 'Hautes-Pyrénées', null, null, null),
  ('Etorki', 'Sau', null, 'Pays basque', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Etorki.jpg'),
  ('Feuille de Dreux', 'Ku', null, 'Cher, Centre Val de Loire', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Feuille%20de%20Dreux.JPG'),
  ('Fort de Béthune', 'Ku', null, 'Béthune, Pas-de-Calais', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20fort%20de%20B%C3%A9thune.jpg'),
  ('Frinault', 'Ku', null, 'et Frinault cendré, Loiret, Centre Val de Loire', null, null, null),
  ('Fougerus', 'Ku', null, 'Brie, Île-de-France', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wikicheese%20-%20Fougerus%20-%2020160123%20-%20001.jpg'),
  ('Foudjou', 'Geit', null, 'Ardèche et Drôme, Rhône-Alpes', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Foudjou%20ard%C3%A9chois.jpg'),
  ('Fourmagée', 'Ku', null, 'Orne, Normandie', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fourmag%C3%A9e%20malax%C3%A9e%20en%20pot%20avec%20du%20cidre.jpg'),
  ('Fourme du Mézenc', 'Ku', null, 'Auvergne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wikicheese%20Clermont-Ferrand%20-%20Bleu%20d%27Auvergne%2020220825-02.jpg'),
  ('Fourme d''Yssingeaux', 'Ku', null, 'Haute-Loire, Auvergne', null, null, null),
  ('Fourme de Roquefort', 'Sau', null, 'Aveyron, AO AOC AOP', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wikicheese%20-%20Roquefort%20-%2020150417%20-%20002.jpg'),
  ('Fourme de Salers', 'Ku', null, 'Cantal, AOC 1961', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Salers%20%28fromage%29%2001.jpg'),
  ('Fromage de Pays', 'Ku', null, 'Auvergne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20de%20Pays.jpg'),
  ('Fromage des Plaines', 'Ku', null, 'Île de la Réunion', null, null, null),
  ('Fromage fermier de Corse', 'Sau', null, '', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20Venachese-Luciani.jpg'),
  ('Fromage fort de la Croix-Rousse', 'Ku', null, 'Lyon', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20fort%20de%20la%20Croix-Rousse.jpg'),
  ('Géromé', 'Ku', null, 'Alsace-Lorraine', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Munster%2001.jpg'),
  ('Gouda français', 'Ku', null, 'Nord-Pas-de-Calais', null, null, null),
  ('Gourmelin', 'Ku', null, 'Pays de la Loire', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Gourmelin.JPG'),
  ('Gournay affiné', 'Ku', null, 'Normandie', null, null, null),
  ('Gournay frais', 'Ku', null, 'Normandie', null, null, null),
  ('Grataron de Arèsches', 'Geit', null, 'Savoie', null, null, null),
  ('Grataron du Beaufortain', 'Geit', null, 'Savoie', null, null, null),
  ('Kaïkou', 'Sau', null, 'Pays basque', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cheese%20ka%C3%AFku.jpg'),
  ('Kidiboo', 'Ku', null, 'Sud-Ouest', null, null, null),
  ('Larron d''Ors', 'Ku', null, 'ou larron, Cambrésis, Nord-Picardie', null, null, null),
  ('Le Barbeillon', 'Geit', null, 'Loir-et-Cher', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20T%C3%A9ton%20de%20Barbeillon%2004.jpg'),
  ('Lormes', 'Geit', null, 'Bourgogne', null, null, null),
  ('Mamirolle', 'Ku', null, 'Franche-Comté', null, null, null),
  ('Manicamp', 'Ku', null, 'Picardie', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20Manicamp%2001.jpg'),
  ('Metton', 'Ku', null, 'Franche-Comté', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cancoillotte.JPG'),
  ('Mimolette vieille', 'Ku', null, 'ou Boule de Lille, Flandre française, Normandie, Pays de la Loire', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mimolette%20vieille%20etuvee.jpg'),
  ('Miromando', 'Ku', null, 'Ardèche', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Myrtilles%20et%20miromando.jpg'),
  ('Mizotte', 'Ku', null, 'Vendée', null, null, null),
  ('Moelleux du Revard', 'Ku', null, 'Savoie', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Moelleux%20du%20Revars.jpg'),
  ('Montbriac', 'Ku', null, 'Haute-Loire, Auvergne', null, null, null),
  ('Murol du Grand Bérioux', 'Ku', null, 'Auvergne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20Murol%20du%20Grand%20B%C3%A9rioux%20-%2020150619%20-%20001.jpg'),
  ('Murolait', 'Ku', null, 'Auvergne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20Murol%20du%20Grand%20B%C3%A9rioux%20-%2020150619%20-%20001.jpg'),
  ('Munster Géromé', 'Ku', null, 'Lorraine, Alsace, AOC 1978', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Munster%2001.jpg'),
  ('Olivet', 'Ku', null, 'Centre, Île-de-France', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Olivet%20cendre-2009.jpg'),
  ('Pannes cendré', 'Ku', null, 'Loiret, Centre Val de Loire', null, null, null),
  ('Pavé d''Auge', 'Ku', null, 'Normandie', null, null, null),
  ('Pavé corrézien', 'Ku', null, 'Corrèze, Limousin', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pav%C3%A9%20corr%C3%A9zien.jpg'),
  ('Pérassu', 'Ku', null, 'ou Pérachu, Haut-Jura, Franche-Comté', null, null, null),
  ('Persillé des Aravis', 'Geit', null, 'Haute-Savoie', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Persilles.jpg'),
  ('Pétafine', 'Ku', null, 'Drôme, Isère', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/P%C3%A9tafine%20onctueuse.jpg'),
  ('Petit Billy', 'Geit', null, 'Ille-et-Vilaine, Bretagne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Petit%20Billy%2001.JPG'),
  ('Pithiviers', 'Ku', null, 'ou bondaroy au foin, Loiret, Centre Val de Loire', null, null, null),
  ('Pourri bressan', 'Ku', null, 'Bresse, Ain', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Pourri%20bressan.JPG'),
  ('Raclette', 'Ku', null, 'Bretagne, Franche-Comté, Rhône-Alpes', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Raclette%20-%20001.jpg'),
  ('Ramequin', 'Ku', null, 'Rhône-Alpes', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Des%20ramequins%20%28fromage%20de%20Saint-Rambert-en-Bugey%29.jpg'),
  ('Rebarba', 'Sau', null, 'Aveyron, Gard, Hérault, Lozère', null, null, null),
  ('Reblochon fermier', 'Ku', null, 'Rhône-Alpes, Haute-Savoie, canton de Thônes AOC 1976', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Reblochon%2011.jpg'),
  ('Rigotte de Pélussin', 'Geit', null, 'Loire', null, null, null),
  ('Rochebaron', 'Ku', null, 'Auvergne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rochebaron%20cheese.JPG'),
  ('Rocroi', 'Ku', null, 'Ardennes', null, null, null),
  ('Rogeret des Cévennes', 'Geit', null, 'Gard', null, null, null),
  ('Rollot', 'Ku', null, 'Picardie', null, null, null),
  ('Roue de Ris', 'Sau', null, 'Puy-de-Dôme, Auvergne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Roue%20de%20Ris.jpeg'),
  ('Rouelle', 'Geit', null, 'Languedoc', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Wikicheese%20-%20Rouelle%20du%20Tarn%20-%2020150417%20-%20001.jpg'),
  ('Saint-florentin', 'Ku', null, 'Yonne, Bourgogne', null, null, null),
  ('Saint-laurent', 'Ku', null, 'Hautes-Alpes', null, null, null),
  ('Saint-paulin', 'Ku', null, 'Bretagne, Normandie, Maine, Nord-Pas-de-Calais {{refnec|et la Réunion}}', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/StPaulin.jpg'),
  ('Savaron', 'Ku', null, 'Auvergne', null, null, null),
  ('Sarasson', 'Ku', null, 'Rhône-Alpes, Auvergne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Sarasson%20nature.jpg'),
  ('Thollon', 'Ku', null, 'Savoie, Haute-Savoie', null, null, null),
  ('Tomme blanche', 'Ku', null, 'Savoie', null, null, null),
  ('Tomme d''Arles', 'Sau', null, 'Camargue, Provence', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tomme%20d%27Arles.jpg'),
  ('Tomme au foin', 'Ku', null, 'Picardie', null, null, null),
  ('Tomme de Montagne', 'Ku', null, 'ou Tomme d''Auvergne, Auvergne', null, null, null),
  ('Tomme de l''Ubaye', 'Ku', null, 'Alpes-de-Haute-Provence', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/St%20Trinit%20-%20Ail%20et%20Tomme%20de%20l%27Ubbaye.jpg'),
  ('Tomme de Rilhac', 'Ku', null, 'Auvergne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tomme%20de%20Rilhac.jpg'),
  ('Tomme forte de Savoie', 'Ku', null, 'Savoie', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tomme%20forte%20de%20Savoie.jpg'),
  ('Tome de Rhuys', 'Ku', null, 'Bretagne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Salon%20de%20l%27agriculture%202011%20-%20tome%20de%20Rhuys%20-%2002.jpg'),
  ('Tomette de brebis', 'Sau', null, 'Hautes-Pyrénées', null, null, null),
  ('Tourrée de l''Aubier', 'Ku', null, 'Moselle, Lorraine', null, null, null),
  ('Tracle', 'Ku', null, 'Bugey, Savoie', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Tracle%20du%20bugey.jpg'),
  ('Tricorne de Marans', 'Sau', null, 'Charentes', null, null, null),
  ('Truffe de Ventadour', 'Geit', null, 'Corrèze', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/WikiCheese%20-%20Truffe%20de%20Ventadour%2006.jpg'),
  ('U Muntagnolu', 'Sau', null, 'Haute-Corse', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20U%20Muntagnolu.jpg'),
  ('Vacherin des Bauges', 'Ku', null, 'Savoie', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vacherin%20des%20bauges.jpg'),
  ('Vacherin du Haut-Doubs', 'Ku', null, 'ou mont d''or, Franche-Comté, AOC 1981', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Vacherin%20du%20haut%20Doubs.jpg'),
  ('Venaco', 'Sau', null, 'Haute-Corse', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20Venachese-Luciani.jpg'),
  ('Vieux pané', 'Ku', null, 'Mayenne', null, null, 'https://commons.wikimedia.org/wiki/Special:FilePath/Fromage%20le%20vieux%20pane.jpg'),
  ('Vieux Samer', 'Ku', null, 'Pas-de-Calais', null, null, null),
  ('Void', 'Ku', null, 'Meuse', null, null, null)
on conflict (name) do nothing;